server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/db_immo
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Spring Security
spring.security.user.name=admin
spring.security.user.password=admin

# JWT
# JWT
jwt.secret=ChangeThisSecretKeyToAStrongRandomValue
jwt.expiration-ms=3600000 